import com.sbz.bank.model.Transaction;
import com.sbz.bank.model.User;
import java.time.LocalDateTime;
import java.util.List;

// If the last transaction was made within the last hour and it's location is more than 100km away
// If the distance between the current transaction and the all other transaction locations is more than 300km
// If the time of transaction is between 1 am and 5 am and the amount is more than 500
// If the transaction amount is 3 times larger than the average transaction amount
// If the last 3 transactions were made within an hour

rule "If the last transaction was made within the last hour and it's location is more than 100km away"
	//agenda-group ""
	when
		$transaction: Transaction(
			sender.getOutboundTransaction() != null,
			sender.getOutboundTransaction().size() >= 1,
			timeOfTransaction.minusHours(1).isBefore(sender.getOutboundTransaction().get(sender.getOutboundTransaction().size() - 1).getTimeOfTransaction()),
			sender.getOutboundTransaction().get(sender.getOutboundTransaction().size() - 1).getLocation().getDistance(location) > 100
			)
	then
		modify($transaction){ setFraudulent(true); }
end

rule "If the distance between the current transaction and the all other transaction locations is more than 300km"
	//agenda-group ""
	when
		$transaction: Transaction(sender.getOutboundTransaction() != null)
		forall($temp: Transaction(location.getDistance($transaction.location) > 300) from $transaction.sender.getOutboundTransaction())
	then
		modify($transaction){ setFraudulent(true); }
end

rule "If the time of transaction is between 1 am and 5 am and the amount is more than 500"
	//agenda-group ""
	when
		$transaction: Transaction(
			timeOfTransaction.getHour() >= 1,
			timeOfTransaction.getHour() <= 5,
			amount >= 500
			)
	then
		modify($transaction){ setFraudulent(true); }
end

rule "If the transaction amount is 3 times larger than the average transaction amount"
	//agenda-group ""
	when
		$transaction: Transaction(sender.getOutboundTransactionsAmountAverage() != 0, sender.getOutboundTransactionsAmountAverage() * 3 <= amount)
	then
		modify($transaction){ setFraudulent(true); }
end

rule "If the last 3 transactions were made within an hour"
	//agenda-group ""
	when
		$transaction: Transaction(
			sender.getOutboundTransaction() != null,
			sender.getOutboundTransaction().size() >= 3,
			timeOfTransaction.minusHours(1).isBefore(sender.getOutboundTransaction().get(sender.getOutboundTransaction().size() - 1).getTimeOfTransaction()),
			timeOfTransaction.minusHours(1).isBefore(sender.getOutboundTransaction().get(sender.getOutboundTransaction().size() - 2).getTimeOfTransaction()),
			timeOfTransaction.minusHours(1).isBefore(sender.getOutboundTransaction().get(sender.getOutboundTransaction().size() - 3).getTimeOfTransaction())
			)
	then
		modify($transaction){ setFraudulent(true); }
end